language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.8'
script: python setup.py test
deploy:
  skip_cleanup: true
  provider: pypi
  password:
    secure: QUn2SdLlNah9H3i77yOjpVjSU7I8oIYmSMuUIZiliUpBgUzndxHIK0kWA5j10ul1iaPviRFKHC8nshHkHgAfxPfQdWFmd+3BESdMzu1AQBxPGUPbfuNiGZjwDPnH2qRApYiM7EV6oMseqz9hIPa37PHbbEES/FeNoWhcmb6SwOijcrpsWwvyKnFyR0j1qRFWSzh+yF8KAB6z6IEI4sR7CXMNCkoUUmhTsd5iAKIvFVngEzthki1mNHemayIk1e/X46hFS7FmPFT/objaWN7ySv6VBjGY2pCVCkfzI2RUe5JN7mvjgjhJqxl5/8EX3KYUZkrYbdiZ/Ixzh29kplD/qikM48r5sTJmtQJCDpkM5+1pGZAdJOrjosUyEprzS4aLIr62oW/McV9aeGstd6ue5/yKwizE173vhmh49bHIIQw6N0S5PhJOGyD+lfRcghYnW0aTrnVJKFxwfVhltcYjxsUEIZNPANZKGw3InpWfM3DZnft7pHBmE1Aq+FmEE78YJdr0VMZtHgKGtbPF6vLaRePOs9Hhogi5out2d7saZrUJ29n3h4gflgbHR8HHjfc5TyJY1Oo3F2PGjE/WxQs8Mqb6noKiCwHqC8Z0yxwMxJr9K0qsZn2Kz9AfEwQXf05zDCvG7+eS43gGN5wBUhD/fm+lx5lGxX492u00Yvnr23Q=
  on:
    tags: true
    repo: svintit/flask-oidc-ext
